#!/usr/bin/env bash
# Verifies W-301's acceptance criterion for real: the generated WardenPolicy CRD's OpenAPI
# schema is enforced by a real Kubernetes API server, not just checked by a Java-side validator
# that some other client could bypass (constitution §8). Applies the CRD generated by
# crd-generator-maven-plugin, then confirms the API server accepts a policy with `timezone` and
# rejects one without.
#
# Manual-run only, matching W-202/W-206's precedent.
#
# Usage:
#   deploy/verify-wardenpolicy-schema.sh              # spins up + tears down its own kind cluster
#   deploy/verify-wardenpolicy-schema.sh --keep        # leaves the cluster up for inspection
#   deploy/verify-wardenpolicy-schema.sh --cluster N   # reuse an existing kind cluster named N
set -euo pipefail

CLUSTER_NAME="warden-crd-schema-check"
KEEP_CLUSTER=false
OWN_CLUSTER=true
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GENERATED_CRD="$REPO_ROOT/warden-crd-model/target/classes/META-INF/fabric8/wardenpolicies.warden.mnemo.io-v1.yml"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep) KEEP_CLUSTER=true; shift ;;
    --cluster) CLUSTER_NAME="$2"; OWN_CLUSTER=false; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

cleanup() {
  if [[ "$KEEP_CLUSTER" == false && "$OWN_CLUSTER" == true ]]; then
    kind delete cluster --name "$CLUSTER_NAME" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

echo "==> building warden-crd-model (regenerates the CRD YAML fresh)"
(cd "$REPO_ROOT" && mvn -q -pl warden-crd-model -am process-classes)
if [[ ! -f "$GENERATED_CRD" ]]; then
  echo "FAIL: expected generated CRD at $GENERATED_CRD, not found" >&2
  exit 1
fi

if [[ "$OWN_CLUSTER" == true ]]; then
  echo "==> creating throwaway kind cluster ($CLUSTER_NAME)"
  kind create cluster --name "$CLUSTER_NAME" >/dev/null
  kubectl --context "kind-$CLUSTER_NAME" wait --for=condition=Ready node --all --timeout=90s >/dev/null
fi

echo "==> applying generated CRD"
kubectl --context "kind-$CLUSTER_NAME" apply -f "$GENERATED_CRD" >/dev/null
kubectl --context "kind-$CLUSTER_NAME" wait --for=condition=Established \
  crd/wardenpolicies.warden.mnemo.io --timeout=30s >/dev/null

fail=false

echo "==> applying a policy WITH timezone — expect the API server to accept it"
if kubectl --context "kind-$CLUSTER_NAME" apply -f "$SCRIPT_DIR/wardenpolicy-sample-valid.yaml" >/dev/null 2>&1; then
  echo "PASS: valid policy accepted"
else
  echo "FAIL: a policy with timezone set was rejected — should have been accepted"
  fail=true
fi

echo "==> applying a policy WITHOUT timezone — expect the API server to reject it"
if kubectl --context "kind-$CLUSTER_NAME" apply -f "$SCRIPT_DIR/wardenpolicy-sample-invalid.yaml" >/tmp/wardenpolicy-invalid-apply.log 2>&1; then
  echo "FAIL: a policy missing timezone was accepted — schema validation is not being enforced"
  cat /tmp/wardenpolicy-invalid-apply.log
  fail=true
else
  if grep -qi "timezone" /tmp/wardenpolicy-invalid-apply.log; then
    echo "PASS: rejected, citing the missing field:"
    sed 's/^/    /' /tmp/wardenpolicy-invalid-apply.log
  else
    echo "FAIL: rejected, but not for the reason expected (no mention of timezone):"
    sed 's/^/    /' /tmp/wardenpolicy-invalid-apply.log
    fail=true
  fi
fi
rm -f /tmp/wardenpolicy-invalid-apply.log

if [[ "$fail" == true ]]; then
  echo "==> RESULT: FAIL"
  exit 1
fi
echo "==> RESULT: PASS — the API server itself enforces timezone as required"
